# Creating Numpy Array

## Basic array

In [1]:
import numpy as np

In [2]:
#1d array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
#multi-dimensional array
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## array with zeros

In [4]:
# 1d array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# multi-dimensional array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Array of ones

In [6]:
# 1d array
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [7]:
# multi-dimensional array
np.ones((5,5),dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Random numbers in ndarrays

In [8]:
#creates array of random numbers
np.random.rand(2,3)

array([[0.29591407, 0.64218061, 0.87027538],
       [0.78052024, 0.95992485, 0.85890317]])

## An array of your choice

In [9]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

## Imatrix

In [10]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Properties of Array Object

In [11]:
#1 Dimension

import numpy
my_list=[10,20,30,40,50]
arr = numpy.array(my_list)

#array
print(arr)

#Type-Datatype of element inside the array/matrix
print("Type : ",arr.dtype)

#Size-no of elements in array/matrix
print("Size : ",arr.size)

#dimension-1d/2d
print("Dimension : ",arr.ndim)

#shape-no of rows and no of columns
print("Shape : ",arr.shape)

[10 20 30 40 50]
Type :  int32
Size :  5
Dimension :  1
Shape :  (5,)


In [12]:
# multidimensional array 

import numpy 
mylist=[[10,20,30],
       [50,60,70],
       [80,90,100]]
matrix = numpy.array(mylist)

#Matrix
print(matrix)

#Type-Datatype of element inside the array/matrix
print("Type : ",matrix.dtype)

#Size-no of elements in 1d and number of rows in nd
print("Size : ",matrix.size)

#dimension-1d/2d
print("Dimension : ",matrix.ndim)

#shape-no of rows and no of columns
print("Shape : ",matrix.shape)


[[ 10  20  30]
 [ 50  60  70]
 [ 80  90 100]]
Type :  int32
Size :  9
Dimension :  2
Shape :  (3, 3)


# Process the elements within the Array/Matrix

In [13]:
#1d

import numpy as np
my_list=[10,20,30,40,50]

for ele in my_list:
    print(ele)


10
20
30
40
50


In [14]:
#2d

import numpy as np
my_list=[[10,20,30],[50,60,70]
         ,[40,50]]
for row in my_list:
    for ele in row:
        print(ele,end=" ")
    print()


10 20 30 
50 60 70 
40 50 


# SubMatrix From Matrix Using Slicing

In [15]:
import numpy as np

mylist=[[10,20,30],
       [50,60,70],
       [80,90,100]]

mat = np.array(mylist)


print("Matrix : \n" , mat)
print()

print("full Matrix 1: \n", mat[0:3,0:3])
print()

print("Sub Matrx 2: \n",mat[0:2,0:3])
print()

print("Sub Matrix 3: \n", mat[1:,1:])
print()


Matrix : 
 [[ 10  20  30]
 [ 50  60  70]
 [ 80  90 100]]

full Matrix 1: 
 [[ 10  20  30]
 [ 50  60  70]
 [ 80  90 100]]

Sub Matrx 2: 
 [[10 20 30]
 [50 60 70]]

Sub Matrix 3: 
 [[ 60  70]
 [ 90 100]]



# Creating 1d array using ndarray()

In [16]:
import numpy as np

n= int(input("Enter Number of elements : "))

arr = np.ndarray(shape=(n), dtype=int)

print("enter %d element "%n)

for ele in range(n):
    arr[ele]=int(input())
    
print(arr)

Enter Number of elements : 5
enter 5 element 
10
20
30
40
50
[10 20 30 40 50]


# Creating 2d array using ndarray()

In [17]:
# 2d Array
import numpy as np

m=int(input("enter number of rows : "))
n=int(input("enter numbers of colums: "))

print("enter %d elements for %dX%d matrix : "%(m*n,m,n))
matrix = np.ndarray(shape=(m,n),dtype=int)

for ele in range(m):
    for ele1 in range(n):
        matrix[ele1]=int(input())

print("Matrix :\n",matrix)


enter number of rows : 2
enter numbers of colums: 2
enter 4 elements for 2X2 matrix : 
60
70
80
90
Matrix :
 [[80 80]
 [90 90]]


# Creating nd array using ndarray()

In [18]:
# nd array 

import numpy as np

arr= np.ndarray(shape=(2,3,3),dtype=int)

val=1

x=arr.shape[0]
y=arr.shape[1]
z=arr.shape[2]

for i in range(x):
    for j in range(y):
        for k in range(z):
            arr[i][j][k]=val
            val=val+1
print(arr)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


# reshape of array


In [19]:
import numpy as np
mylist=[10,20,30,40,50,60,70,80]
arr = np.array(mylist)
print("Dimension: ",arr.ndim)
print(arr)
print()

#reshape
res = arr.reshape(2,2,2)
print("Dimension: ",res.ndim)
print(res)


Dimension:  1
[10 20 30 40 50 60 70 80]

Dimension:  3
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
